CREATE DATABASE IF NOT EXISTS aoa CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE aoa;

CREATE TABLE IF NOT EXISTS inquiries (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(190) NOT NULL,
  project_type VARCHAR(60) NOT NULL,
  budget VARCHAR(60) NOT NULL,
  message TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_inquiries_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
